DROP DATABASE IF EXISTS "mstDBv1" ;
ALTER USER mstDBUser WITH PASSWORD 'dataStoreMST' ;
CREATE DATABASE "mstDBv1" TEMPLATE=template1 ;
GRANT ALL PRIVILEGES ON DATABASE "mstDBv1" to mstDBUser ;
\connect "mstDBv1" ;
GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC to mstDBv1 ;
